### ISSUE TITLE
BinaryReader error on SpaceWard devnet

### ISSUE THREAD

**Issue by jjheywood** [warden-protocol/wardenprotocol#406]
When trying to use SpaceWard on devnet I'm getting the error message below after 30 seconds or so.

```
ReferenceError: BinaryReader is not defined
    at Object.decode (index-CdeNzXNm.js:371:22264)
    at index-CdeNzXNm.js:604:268598
    at Array.map (<anonymous>)
    at useModuleAccount (index-CdeNzXNm.js:604:268574)
    at useNewAction (index-CdeNzXNm.js:604:268952)
    at useRequestSignature (index-CdeNzXNm.js:604:269872)
    at useEthereumTx (index-CdeNzXNm.js:670:143531)
    at WalletConnect (index-CdeNzXNm.js:706:59818)
    at Xh (index-CdeNzXNm.js:38:22045)
    at dj (index-CdeNzXNm.js:40:3557)
```

**Comment by pitasi** [comment]
fixed in #408
